name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    # Use an Ubuntu environment for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checkout the code from the repository

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
        # Set up Java with the Temurin distribution, version 11

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        # Build the project using Maven

      - name: Run tests
        run: mvn test
        # Run unit tests using Maven

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/
        # Save build artifacts (from the Maven target directory) in the repository

  deploy:
    needs: build
    # Run deploy job only if the build job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checkout the code to access build artifacts

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
        # Download saved build artifacts from the previous job

      - name: Deploy to Staging
        run: echo "Deploying to staging..."
        # Add your deployment script or command here
